name: Formatters & Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project (pull-request)
        uses: actions/checkout@v2.3.2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Run checks
        run: sbt ci-test
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Run post-conditions
        run: test -f .github/actions.yml && eval "$(yq e '.post.ci // "true"' .github/actions.yml)" || true
      - name: Automerge Scala Steward PRs
        if: success() && github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Scala Steward')
        uses: ridedott/merge-me-action@v1.1.36
        with:
          GITHUB_LOGIN: 47erbot
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
